# Generated by Django 5.2.11 on 2026-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_visibility_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
